addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.8")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"   % "0.14.8")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"  % "0.7.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"   % "3.8")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"        % "2.0.0")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.1.0")
addSbtPlugin("com.47deg"                 % "sbt-microsites" % "0.9.7")
