openapi: 3.0.1
info:
  title: Sample docs
  version: 0.0.1
paths:
  /version:
    get:
      description: Return current version details.
      operationId: getVersion
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionDeployed'
        default:
          description: ''
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    VersionDeployed:
      required:
        - buildDate
        - buildSha
      type: object
      properties:
        buildDate:
          type: string
        buildSha:
          type: string
